CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    mobile VARCHAR2(15),
    password VARCHAR2(50),
    address VARCHAR2(255)
);


CREATE TABLE farmers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE, -- Login ke liye zaroori
    locality VARCHAR2(100),
    upi_id VARCHAR2(50),
    password VARCHAR2(50) NOT NULL
);

CREATE TABLE products (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(200),
    description VARCHAR2(500),
    category VARCHAR2(100),
    price NUMBER(10,2),
    stock NUMBER,
    image VARCHAR2(300),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE cart (
    cart_id VARCHAR2(50) PRIMARY KEY,
    user_email VARCHAR2(100),
    p_id VARCHAR2(50),
    p_name VARCHAR2(100),
    price NUMBER(10, 2), -- 10 digits total, 2 decimal ke baad
    quantity NUMBER(10),
    CONSTRAINT unique_cart_item UNIQUE (user_email, p_id)
);


CREATE TABLE orders (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_email VARCHAR2(100),
    product_name VARCHAR2(200),
    amount NUMBER(10,2),
    status VARCHAR2(30),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id VARCHAR2(200),
    payment_id VARCHAR2(200),
    signature VARCHAR2(500),
    user_email VARCHAR2(200),
    amount NUMBER,
    status VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE waste_requests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_email VARCHAR2(100) NOT NULL,
    acres NUMBER(10, 2) NOT NULL,
    pickup_date DATE NOT NULL,
    location VARCHAR2(255) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, SCHEDULED, REJECTED, COMPLETED
    request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE admin (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL
);

-- 2. Insert Default Admin
INSERT INTO admin (full_name, email, password) 
VALUES ('Main Admin', 'admin@gmail.com', 'admin123');

COMMIT;




